import ApiError from "../../helpers/apiError.js"
import { generateInviteToken, hashInviteToken } from "../../helpers/crypto.js";
import Conversation from "../conversation/conversation.model.js";
import User from "../user/user.model.js"
import Invite from "./invite.model.js";

// Generate invite token
export const generateInviteService = async({ userId }) => {
    const user = await User.findById(userId);

    if (!user)
        throw new ApiError(404, "User not found", "USER_NOT_FOUND");

    const { inviteToken, hash } = generateInviteToken()

    const threeDaysExpire = Date.now() + 72 * 60 * 60 * 1000;

    const invite = await Invite.create({
        token: hash,
        inviterId: userId,
        expiredAt: threeDaysExpire,
    })

    await invite.save();

    return { inviteToken };
}


export const verifyInviteService = async({ token }) => {
    if (!token)
        throw new ApiError(400, "Invite token missing", "INVITE_TOKEN_MISSING")

    const hashedToken = hashInviteToken(token)

    const invite = await Invite.findOne({
        token: hashedToken,
    })

    if (!invite)
        throw new ApiError(400, "Token is invalid or expired", "INVITE_TOKEN_EXPIRED")

    const userId = invite.inviterId;
    if (!userId)
        throw new ApiError(403, "Link generated by unauthorized user", "INVITE_LINK_UNAUTHORIZED");

    const user = await User.findById(userId).select("username avatar accountStatus")

    return { user };
}

export const acceptInviteService = async({ token, userId }) => {
    if (!userId) // logged in user
        throw new ApiError(400, "UserId is required ", "USER_REQUIRED")

    if (!token)
        throw new ApiError(400, "Invite token missing or expired", "INVITE_TOKEN_MISSING");

    // Hash the token
    const hashedToken = hashInviteToken(token);

    // find the invite document with the token
    const invite = await Invite.findOne({ // A user,
        token: hashedToken,
        inviteStatus: "pending"
    })

    if (!invite) {
        throw new ApiError(404, "Invite message not found", "INVITE_MISSING")
    }

    const inviter = invite.inviterId;

    // check self joining
    if (inviter.toString() === userId.toString())
        throw new ApiError(400, "You cannot accept your own invite link")

    let conversation;
    conversation = await Conversation.findOne({
        participants: {
            $all: [userId, inviter],
        }
    });

    // if conversation not found then we crete conversation with userId and inviter
    if (!conversation) {
        conversation = await Conversation.create({
            participants: [userId, inviter],
            lastMessage: null,
            unreadCount: {
                [userId]: 0,
                [inviter]: 0
            }
        });
    }

    // update the data of invite status
    invite.inviteStatus = "accepted";

    await invite.save();

    return { conversation, inviter };
}
