import ApiError from "../../helpers/apiError.js";
import { generateInviteToken, hashInviteToken } from "../../helpers/crypto.js";
import { getIO } from "../../socket.server.js";
import Conversation from "../conversation/conversation.model.js";
import User from "../user/user.model.js";
import Invite from "./invite.model.js";

// Generate invite token
export const generateInviteService = async({ userId }) => {
    const user = await User.findById(userId);

    if (!user)
        throw new ApiError(404, "User not found", "USER_NOT_FOUND");

    const { inviteToken, hash } = generateInviteToken()

    const threeDaysExpire = Date.now() + 72 * 60 * 60 * 1000;

    await Invite.create({
        token: hash,
        inviterId: userId,
        expiredAt: threeDaysExpire,
    })

    // await invite.save();

    return { inviteToken };
}

// Verify the Invite link
export const verifyInviteService = async({ token }) => {
    if (!token)
        throw new ApiError(400, "Invite token missing", "INVITE_TOKEN_MISSING")

    const hashedToken = hashInviteToken(token)

    const invite = await Invite.findOne({token: hashedToken})

    if (!invite)
        throw new ApiError(404, "Invite link is invalid or expired", "INVITE_TOKEN_EXPIRED") // means mongo ttl deleted this

    if (invite.inviteStatus === "accepted") {
        throw new ApiError(410, "The inivitation link is already used", "INVITE_TOKEN_USED");
    }

    const userId = invite.inviterId;
    if (!userId)
        throw new ApiError(403, "Link generated by unauthorized user", "INVITE_LINK_UNAUTHORIZED");

    // if status is pending after above checks then it return the data;
    const user = await User.findById(userId).select("username avatar accountStatus")

    return { user };
}

export const acceptInviteService = async({ token, userId }) => {
    if (!userId) // logged in user
        throw new ApiError(400, "UserId is required ", "USER_REQUIRED")

    if (!token)
        throw new ApiError(400, "Invite token missing or expired", "INVITE_TOKEN_MISSING");

    // Hash the token
    const hashedToken = hashInviteToken(token);

    // find the invite document with the token
    const invite = await Invite.findOneAndUpdate({
        token: hashedToken,
        inviteStatus: "pending"
    }, {
        $set: { inviteStatus: "accepted" }
    }, { new: true });

    if (!invite) {
        throw new ApiError(404, "Invite message not found", "INVITE_MISSING")
    }

    const inviter = invite.inviterId; // find the user, who generate the invite link
    // check self joining, self chat is allowed in message module and Its in MVP PLAN

    let conversation;
    if (inviter.toString() === userId.toString()) {

        // create self chat conversation
        conversation = await Conversation.findOne({
            participants: {
                $all: [userId],
                $size: 1,
            },
            type: "private"
        });

        if (!conversation) {
            conversation = await Conversation.create({
                participants: [inviter],
                type: "private",
                lastMessage: null,
                unreadCount: {
                    [userId]: 0
                }
            });
        }

    } else {
        // 1 To 1 chat
        conversation = await Conversation.findOne({
            participants: {
                $all: [userId, inviter],
                $size: 2,
            },
            type: "private"
        });

        // if conversation not found then we crete conversation with userId and inviter
        if (!conversation) { // created one document of conversation
            conversation = await Conversation.create({
                participants: [userId, inviter],
                lastMessage: null,
                unreadCount: {
                    [userId]: 0,
                    [inviter]: 0
                }
            });
        }
    }

    // let change the expected with conversation services strcuture
    const conversationWithParticipants = await Conversation.findById(conversation._id)
        .populate("participants", "username avatar")
        .populate("lastMessage")
        .populate("lastMessage", "content messageType senderId")

        const otherUser = conversationWithParticipants.participants.find(
            user => user._id.toString() !== inviter.toString()
        ) || conversationWithParticipants.participants[0];

        const conversationPayload = {
            _id: conversation._id,
            chatWith: otherUser, // here userId the new user who logged in make and return to /chat with inviter
            lastMessage: conversationWithParticipants.lastMessage ? {
                content: conversationWithParticipants.lastMessage.content,
                messageType: conversationWithParticipants.lastMessage.messageType,
                senderId: conversationWithParticipants.lastMessage.senderId
            }
            : null,
            lastMessageAt: conversationWithParticipants.lastMessageAt,
            unreadCount: conversationWithParticipants.unreadCount.get(inviter.toString()) ?? 0
        };

        console.log("conversation payload: ",conversationPayload)

    // Socker event for inviter, inform to inviter that someone accepte your invitation
    const io =  getIO(); // conversation here is the mongodb one document not matched with what frontend needs
    io.to(`user:${inviter.toString()}`).emit("conversation_created", conversationPayload);


    return { conversation, inviter };
}
